<% common = "--format html --out reports/results.html --format json --out reports/reports.json --format pretty --color --no-source --tags 'not @skip'" %>
android_real: <%= common %> PLATFORM=android APP_PATH=./apks/AndroidCalculator.apk
android_emu: <%= common %> PLATFORM=android APP_PATH=./apks/AndroidCalculator.apk
